# Generated by Django 4.2.4 on 2024-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fhawaiilah.com%2F&psig=AOvVaw0yiAdP6QYIcUIHA_VhKJoW&ust=1719248599575000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLiRs7qa8oYDFQAAAAAdAAAAABAJ",
                max_length=500,
            ),
        ),
    ]
