# Generated by Django 4.2.4 on 2024-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.food4fuel.com%2Fproduct%2Fsingle-meal%2F&psig=AOvVaw0yiAdP6QYIcUIHA_VhKJoW&ust=1719248599575000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLiRs7qa8oYDFQAAAAAdAAAAABAR",
                upload_to="images",
            ),
        ),
    ]
