# Generated by Django 4.2.4 on 2024-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                default="https://cdn.pixabay.com/photo/2017/09/30/15/10/plate-2802332_640.jpg",
                upload_to="images",
            ),
        ),
    ]
